nbaData_team <- team_season nbaData_team$win_per <- nbaData_team$won/(nbaData_team$won+nbaData_team$lost) normalize <- function(x) { return ((x - min(x)) / (max(x) - min(x))) } 
nbaData_team$o_fgm <- normalize(nbaData_team$o_fgm) nbaData_team$o_fga <- normalize(nbaData_team$o_fga) nbaData_team$o_ftm <- normalize(nbaData_team$o_ftm) nbaData_team$o_fta <- normalize(nbaData_team$o_fta) nbaData_team$o_oreb <- normalize(nbaData_team$o_oreb) nbaData_team$o_dreb <- normalize(nbaData_team$o_dreb) nbaData_team$o_reb <- normalize(nbaData_team$o_reb) nbaData_team$o_asts <- normalize(nbaData_team$o_asts) nbaData_team$o_pf <- normalize(nbaData_team$o_pf) 
 
nbaData_team$o_stl <- normalize(nbaData_team$o_stl) nbaData_team$o_to <- normalize(nbaData_team$o_to) nbaData_team$o_blk <- normalize(nbaData_team$o_blk) nbaData_team$o_3pm <- normalize(nbaData_team$o_3pm) nbaData_team$o_3pa <- normalize(nbaData_team$o_3pa) nbaData_team$o_pts <- normalize(nbaData_team$o_pts) 
nbaData_team$d_fgm <- normalize(nbaData_team$d_fgm) nbaData_team$d_fga <- normalize(nbaData_team$d_fga) nbaData_team$d_ftm <- normalize(nbaData_team$d_ftm) nbaData_team$d_fta <- normalize(nbaData_team$d_fta) nbaData_team$d_oreb <- normalize(nbaData_team$d_oreb) nbaData_team$d_dreb <- normalize(nbaData_team$d_dreb) nbaData_team$d_reb <- normalize(nbaData_team$d_reb) nbaData_team$d_asts <- normalize(nbaData_team$d_asts) nbaData_team$d_pf <- normalize(nbaData_team$d_pf) nbaData_team$d_stl <- normalize(nbaData_team$d_stl) nbaData_team$d_to <- normalize(nbaData_team$d_to) nbaData_team$d_blk <- normalize(nbaData_team$d_blk) nbaData_team$d_3pm <- normalize(nbaData_team$d_3pm) nbaData_team$d_3pa <- normalize(nbaData_team$d_3pa) nbaData_team$d_pts <- normalize(nbaData_team$d_pts) 
nbaData_team$win_per <- normalize(nbaData_team$win_per) 
set.seed(214) ind <- sample(2, nrow(nbaData_team), replace=TRUE, prob=c(0.75, 0.25)) nba_TrainingData <- nbaData_team[ind==1,] nba_TestData <- nbaData_team[ind==2,] 
model_team_null = lm(win_per ~ 1, data = nba_TrainingData) # Includes only the intercept model_team_full = lm(win_per ~ d_fgm + d_fga + d_fta + d_oreb + d_dreb + d_asts + d_stl + d_blk + d_to + d_pf + d_3pm + d_3pa + d_pts + o_fgm + o_fga + o_ftm + o_fta + o_oreb + o_dreb + o_asts + o_stl + o_blk + o_to + o_pf + o_3pm + o_3pa + o_pts, data = nba_TrainingData) 
step(model_team_null, scope=list(lower=model_team_null, upper=model_team_full), direction="both") 
model_team_stepvars <- lm(formula = win_per ~ d_pts + o_pts + o_3pm + d_3pm, data = nba_TrainingData) summary(model_team_stepvars) 
test_data_pred <- predict(model_team_stepvars, newdata = nba_TestData) summary(test_data_pred) 
test_data_pred_nba <- table(test_data_pred, nba_TestData$win_per) test_data_pred_nba 
test_data <- cbind(nba_TestData, as.data.frame(test_data_pred)) write.csv(test_data, "D:/Desktop/StatsProject/test_data.csv") 
